vscode:
  extensions:
    - alygin.vscode-tlaplus@1.4.0:9lZudjtb8tiPCbz+NmnaCg==

tasks:
  - init: git config --global alias.slog 'log --pretty=oneline --abbrev-commit'
  - init: git config --global alias.co checkout
